# docker-compose.yml

services:
  v1-bot: &v1bot
    build:
      context: ./bots/v1-bot
      dockerfile: Dockerfile
      target: runtime
    env_file:
      - ./bots/v1-bot/.env
    volumes:
      - ./bots/v1-bot/src:/usr/src/app/src
      - ./bots/v1-bot/node_modules:/usr/src/app/node_modules
    environment:
      DEPLOY_ON_STARTUP: ${DEPLOY_ON_STARTUP:-false}
    restart: unless-stopped
  v1-bot-test:
    <<: *v1bot
    build:
      context: ./bots/v1-bot
      dockerfile: Dockerfile
      target: test
    command: sh -c "npm test && tail -f /dev/null"
    environment:
      DEPLOY_ON_STARTUP: 'false'
    restart: 'no'

volumes:
  v1_bot_node_modules:
